spring:

  datasource:
    url: jdbc:mysql://localhost:3306/localdata
    username: root
    password: aziz1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true  # Set to true to view SQL queries in the logs
    hibernate:

      ddl-auto: update
    properties:
      hibernate:
        format_sql: true  # Format SQL for better readability


server:
  port: 8081


